// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./core_ed25519.js')
  await import('./crypto_aead_chacha20poly1305_ietf.js')
  await import('./crypto_aead_xchacha20poly1305_ietf.js')
  await import('./crypto_auth.js')
  await import('./crypto_box.js')
  await import('./crypto_generichash.js')
  await import('./crypto_hash.js')
  await import('./crypto_hash_sha256.js')
  await import('./crypto_hash_sha512.js')
  await import('./crypto_kdf.js')
  await import('./crypto_kx.js')
  await import('./crypto_onetimeauth.js')
  await import('./crypto_pwhash.js')
  await import('./crypto_pwhash_scryptsalsa208sha256.js')
  await import('./crypto_scalarmult.js')
  await import('./crypto_secretbox.js')
  await import('./crypto_secretstream.js')
  await import('./crypto_shorthash.js')
  await import('./crypto_sign.js')
  await import('./crypto_stream.js')
  await import('./crypto_stream_chacha20.js')
  await import('./crypto_stream_chacha20_ietf.js')
  await import('./extension_pbkdf2.js')
  await import('./extension_tweak_ed25519.js')
  await import('./helpers.js')
  await import('./memory.js')
  await import('./padding.js')
  await import('./randombytes.js')
  await import('./vectors.js')
  await import('./fastcalls.js')

  test.resume()
}
