name: Build Status
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: choco upgrade llvm
      if: ${{ matrix.os == 'windows-latest' }}
    - run: npm install -g bare-runtime bare-make
    - run: npm install
    - run: bare-make generate --debug
    - run: bare-make build
    - run: bare-make install
    - run: npm test
